# Generated by Django 6.0.3 on 2026-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_items_description_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
